### ISSUE TITLE
eclipse bash editor is not showing in the list of editor selection for sh files

### ISSUE THREAD

**Issue by souradeep07** [de-jcup/eclipse-bash-editor#195]
eclipse bash editor is not coming in the list of editor selection for sh files. I am using Eclipse IDE for Enterprise Java Developers: 2020-03 (4.15.0)

![image](https://user-images.githubusercontent.com/30365437/82408099-78bb6c00-9a88-11ea-9aed-90067366d2d5.png)

![image](https://user-images.githubusercontent.com/30365437/82408163-a1436600-9a88-11ea-8410-347418ea83b3.png)

**Comment by de-jcup** [comment]
I tried following:

- Installed a fresh Eclipse IDE 2020-03 JEE package to a windows machine
- Started Open JDK 14
-  Created an empty test file "test.sh"
- Eclipse suggested me to install something from marketplace and I selected "Bash editor"
- After eclipse restart the editor did automatically open on double click  on test.sh as shown in next picture

![image](https://user-images.githubusercontent.com/11644753/82735663-8dfff700-9d23-11ea-8f16-14f5b29b35b0.png)

Also trying an "Open with ..." the selection editor does show bash editor:
![image](https://user-images.githubusercontent.com/11644753/82735713-f222bb00-9d23-11ea-8e42-fffa36e79a0c.png)

So I absolutely not able to reproduce the problem - I suggest you uninstall bash editor and then install again. If you have still problems, please look into error log and search for some  bash editor specific errors - if there are any. If you find something please post it here.

**Comment by souradeep07** [comment]
@de-jcup I am using Oracle JDK 1.8 Can you please confirm if the bash editor supports jdk 1.8 ?

**Comment by de-jcup** [comment]
Yes. It works with Java 8 - I am always using OpenJDK 8 at  development runtime and also for plugin builds. 

- Have you already checked that bash editor is really installed/started?
![image](https://user-images.githubusercontent.com/11644753/82741022-61150980-9d4e-11ea-8f96-d836ed1d1ccc.png)

If its not listed there the installation or startup failed and the plugin is not available and so not listed.
It would be interesting to see eclipse logs ins such case.

- Have you installed it by eclipse marketplace or from somewhere else?

- If you have still problems you could try to download a complete new JEE package (as I did) and just install bash editor by eclipse market place. If this works your existing eclipse instance could be corrupted

**Comment by brgillis** [comment]
I'm having this issue as well. I'm using:

Eclipse IDE for C/C++ Developers

Version: 2018-12 (4.10.0)
Build id: 20181214-0600

This comes in a packaged Virtual Machine set up for the development environment I'm working with, so I can't easily change it.

I installed Bash Editor through the Eclipse marketplace, restarted Eclipse. When It tried to open a .sh file, it didn't open Bash Editor (just the system text editor, as before), and I also couldn't find it in the list of editors. I tried uninstalling the reinstalling Bash Editor, but no luck. It does indeed show up as installed though.

I've attached the Eclipse log in hopes that it will help.

[eclipse_errors.txt](https://github.com/de-jcup/eclipse-bash-editor/files/4711512/eclipse_errors.txt)

**Comment by de-jcup** [comment]
I just released version 2.3.0 at eclipse marketplace. Please try out this version.

If you have still problems here, then please do following:
- open the view "Error Log" and press "Delete Log" button (really remove all error logs)
![image](https://user-images.githubusercontent.com/11644753/83931241-e6aba700-a79b-11ea-9fd3-258bb7d59884.png)
- then restart your eclipse
- open again view "Error Log"
- search for errors related to bash editor plugin
- paste information into this issue (picture and/or text)

**Comment by brgillis** [comment]
Thank you. I tried this, and unfortunately it's still not working. I tried completely uninstalling and reinstalling it to be sure, and the same issue persists.

When I tried to see if anything shows up in the Error log, nothing related to Bash Editor shows up, even after trying to open a *.sh file. There are just 4 warnings and 1 info message related to org.eclipse plugins (I can upload a screenshot of this if you think it might be useful).

**Comment by souradeep07** [comment]
After updating to version 2.3.0, the bash editor is working for me. Thanks for your support @de-jcup

**Comment by de-jcup** [comment]
I add the editor at https://github.com/de-jcup/eclipse-bash-editor/blob/e661259a430453c04fc15773cc1fd3f05f7b3d05/basheditor-plugin/plugin.xml#L64-L74
in standard way, so should normally always working.

It smells like an eclipse bug - I checked https://bugs.eclipse.org/ but I did not found an issue for this behaviour. 

@brgillis : You use an older eclipse version - I would recommend to upgrade to current version 2020‑06 (https://www.eclipse.org/downloads/packages/release/2020-06/r/eclipse-ide-cc-developers)  and try again.
